### ISSUE TITLE
Hey Dubbeck here I couldn't think of any other way of contacting you

### ISSUE THREAD

**Issue by DubbEck** [davioliva16/create-aquatic-ambitions#4]
Yo man I luvvvv what you did with this mod, I'm glad you felt inspired by my project (Prismarine Automation) and I'm not here to take a piss. Aquatic Ambitions does what I could only wish my mod did, I'm blown away by the quality (and creativity). Like I REALLY REALLY like the bulk channeling feature. Sorry again for littering the issues tab on your GitHub, oh and slide your discord pls...

**Comment by davioliva16** [comment]
Hey! Yeah I really think the Prismarine to copper recipes makes so much sense, and its definitely the best renewable copper concept I have seen, and really wanted to expand the idea. My discord is just davioliva
