### ISSUE TITLE
Quilt support?

### ISSUE THREAD

**Issue by ImBehinYa** [davioliva16/create-aquatic-ambitions#6]
![image](https://github.com/davioliva16/create-aquatic-ambitions/assets/63367722/cfc6d374-ba86-4392-97d6-e7a0d26e6c0d)

quiltet fabric loader does utilize 0.91.0 not 0.92.0

**Comment by NolanHewitt** [comment]
You can override this and the game will start, but it seems none of the recipes or additions from this mod actually work on quilt when doing that.

**Comment by NolanHewitt** [comment]
Update, QFAPI updated and now this mod does work on quilt.

**Comment by davioliva16** [comment]
Great, I'll close the issue

**Comment by NolanHewitt** [comment]
Actually, it looks like the conduit channeling recipes don't work. They don't even show up in REI.

The other recipes do load in and work though.

**Comment by NolanHewitt** [comment]
The recipes for conduit channeling don't seem to show in REI. They do work though.

**Comment by davioliva16** [comment]
REI and EMI require custom code, I need to look into it later
